<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "timetable".
 *
 * @property integer $id
 * @property integer $start_time
 * @property integer $end_time
 * @property integer $patient_id
 * @property string $full_name
 * @property integer $doctor_id
 * @property integer $manager_id
 * @property string $notes
 * @property string $phone
 * @property integer $primary
 */
class Timetable extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'timetable';
    }

    public function beforeSave($insert)
    {
        $this->date = strtotime($this->date);


        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date'], 'string', 'max'=>11],
            [['start_time','end_time' ], 'string', 'max'=>5 ],
            [['patient_id', 'doctor_id', 'manager_id', 'primary'], 'integer'],
            [['date','start_time','end_time', 'doctor_id', 'manager_id'], 'required'],
            [['notes'], 'string'],
            [['full_name'], 'string', 'max' => 255],
            [['phone'], 'string', 'max' => 25],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'date' => Yii::t('app', 'Дата'),
            'start_time' => Yii::t('app', 'Начало приема'),
            'end_time' => Yii::t('app', 'Конец приема'),
            'patient_id' => Yii::t('app', 'ID пациента'),
            'full_name' => Yii::t('app', 'ФИО'),
            'doctor_id' => Yii::t('app', 'Выберите доктора'),
            'manager_id' => Yii::t('app', 'Менеджер'),
            'notes' => Yii::t('app', 'Заметки'),
            'phone' => Yii::t('app', 'Телефоный номер '),
            'primary' => Yii::t('app', 'Первичный'),
        ];
    }
}
